on:
  workflow_dispatch:
    inputs:
      terraform_operation:
        description: "Terraform operation: plan, apply, destroy"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Apply/Plan/Destroy'
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_VAR_credential_file: ${{ secrets.TF_VAR_CREDENTIAL_FILE }}
      TF_VAR_project: ${{ secrets.TF_VAR_PROJECT }}
      TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
      TF_VAR_zone: ${{ secrets.TF_VAR_ZONE }}
      BUCKET_NAME: ${{ secrets.BACKEND_BUCKET_NAME }}
      WORKDIR: ./terraform

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.TF_VAR_CREDENTIAL_FILE }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      # with:
      #   cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      run: terraform init -backend-config="bucket=${{ env.BUCKET_NAME }}"
      env:
        working-directory: ${{ env.WORKDIR }}

    - name: Terraform Plan
      if: "${{ github.event.inputs.terraform_operation == 'plan' }}"
      run: terraform plan -input=false

      
    - name: Terraform Apply
      if: "${{ github.event.inputs.terraform_operation == 'apply' }}"
      run: terraform apply -auto-approve -input=false
      env:
        working-directory: ${{ env.WORKDIR }}
    - name: Terraform Destroy
      if: "${{ github.event.inputs.terraform_operation == 'destroy' }}"
      run: terraform destroy -auto-approve -input=false
      env:
        working-directory: ${{ env.WORKDIR }}